import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Banner from "../components/banner";
import Card from "../components/card";
import { CoffeeStores } from "../data/coffee-stores";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("first");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS App Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.cardLayout}>
          {CoffeeStores.map((item) => {
            return (
              <Card
                key={item.id}
                name={item.name}
                imgUrl={item.imgUrl}
                href={`/coffee-store/${item.id}`}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
