import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { useEffect } from "react";

export async function getStaticProps() {
  const res = await fetch("https://ppmob.takomo.vn/v1/4/client/register", {
    method: "POST",
    mode: "no-cors",
    credentials: "same-origin",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify({ phone: "0100200300" }),
  });

  const CoffeeStores = await res.json();

  return {
    props: {
      CoffeeStores,
    },
  };
}

export default function Home({ CoffeeStores }) {
  const handleOnBannerBtnClick = () => {
    console.log("first");
  };

  useEffect(() => {
    console.log(CoffeeStores);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Stores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View Stores Nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.cardLayout}>
          {/* {CoffeeStores.data.map((item) => {
            return (
              <Card
                key={item.id}
                name={item.attributes.name}
                imgUrl={item.attributes.imgUrl}
                href={`/coffee-store/${item.id}`}
              />
            );
          })} */}
        </div>
      </main>
    </div>
  );
}
